Add build version report
wavefrontHQ/wavefront-flask-sdk-python pull request #3
Opened 2020-10-06 17:24 UTC by xshipeng

The build version is reported as "~sdk.python.flask.sender.version"

2020-10-06 19:29 UTC, hanwavefront requested changes

2020-10-06 19:29 UTC, hanwavefront commented on wavefront_flask_sdk/flask_tracing.py
> +                prefix='{}.flask.sender'.format(SDK_METRIC_PREFIX))
let's name the metric `*.flask.version` instead of `*.flask.sender.version`

2020-10-06 22:00 UTC, hanwavefront approved these changes
LGTM

2020-10-08 20:52 UTC, haosong approved these changes

2020-10-08 21:51 UTC, merged